<BoardRow>:
    orientation: "horizontal"
    size_hint_y: None
    height: dp(36)
    size_hint_x: 1
    spacing: dp(8)

    MDLabel:
        text: root.board
        halign: "center"
        size_hint_x: 0.25

    MDLabel:
        text: root.score
        halign: "center"
        size_hint_x: 0.25

    MDLabel:
        text: root.team_score
        halign: "center"
        size_hint_x: 0.25

    MDLabel:
        text: root.imps
        halign: "center"
        size_hint_x: 0.25
