# kv/cusom_widgets.kv

<WhiteTextField@MDTextField>:
    mode: "fill"
    fill_color: 1, 1, 1, 1
    text_color_normal: 0, 0, 0, 1
    text_color_focus: 0, 0, 0, 1
    hint_text_color_normal: 0.5, 0.5, 0.5, 1
    size_hint_y: None
    height: dp(56)
    radius: [10, 10, 10, 10]
    allow_copy: False

<SuitButton>:
    font_name: "DejaVuSans"
    font_size: "20sp"
    size_hint: 1, None
    height: dp(36)
