# kv/event_list.kv

<EventList>:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: f"Events"
            right_action_items: [["dots-vertical", lambda x: root.open_menu(x)]]

        ScrollView:
            MDList:
                id: event_list

        MDFloatingActionButton:
            icon: "plus"
            pos_hint: {"right": 0.95, "y": 0.05}
            on_release: root.go_event_form()
